## Notes 
### Required installing Oracle JAVA 8 to get javabridge installed
### Then, I was able to install py-causal from https://bd2kccd.github.io/docs/py-causal/
### GFCI is slower than RFCI, but more accurate (SPIRTES), GFCI and RFCI account for unobserved variables, FGES assumes no unobserved variables.

Structure Learning Performance Guarantees If the assumptions in the previous section hold, then in the large sample limit, the CBN structure output by GFCId will contain an edge of one of four kinds between Xand Y   if and only if Xand Yare not independent conditional on any subset of the other measured variables of less than or equal to a specified size. In addition, there is (1) an arc X->Y   if and only if Xdirectly or indirectly causes Y, and Y   does not directly or indirectly cause X; (2) an edge X <-->Y   if and only if X   is not a direct or indirect cause of Yand Y   is not a direct or indirect cause of X(which can only occur if there are latent confounders of Xand some other variable or Yand some other variable; (3) an edge Xo->Y   only if Yis not a direct or indirect cause of X, but Xmay or may not be an indirect cause of Y; (4) an edge X o–o Y   indicates that Xand Y   are dependent no matter what subset of observed variables is conditioned on, but contains no orientation information (X   may be a direct or indirect cause of Y, and Ymay be an indirect cause of X, or there may be a latent common cause of Xand Y.

In [ ]:
# This is for continous data.
# generate some toy data:
SIZE = 20000
a = np.random.normal(size=SIZE, scale = 1)
b = np.random.normal(size=SIZE, scale = 1)
c = np.random.normal(size=SIZE, scale = 1)
d = np.random.normal(size=SIZE, scale = 1)
e = np.random.normal(size=SIZE, scale = 1)

f= a + b + c + d + e + np.random.normal(size=SIZE, scale = 1)
g = f + np.random.normal(size=SIZE, scale = 1)

# load the data into a dataframe:
df = pd.DataFrame({'a' : a,'b' : b, 'c' : c, 'd' : d,'e' : e,'f':f, 'g':g})
import pandas as pd
from pycausal.pycausal import pycausal as pc
from pycausal import search as s
pc = pc()
pc.start_vm(java_max_heap_size = '500M')
from pycausal import prior as p

tetrad = s.tetradrunner()
#GFCI = Greedy Fast Causal Interference (GFCI) 
# bdeu = Bayesian Dirichlet likelihood equivalence and uniform
tetrad.run(algoId = 'gfci', dfs = df, testId = 'sem-bic', scoreId = 'sem-bic', dataType = 'continuous',
           structurePrior = 1.0, samplePrior = 1.0, maxDegree = -1, maxPathLength = -1, 
           completeRuleSetUsed = False, faithfulnessAssumed = True, verbose = True)

import pydot
from IPython.display import SVG
dot_str = pc.tetradGraphToDot(tetrad.getTetradGraph())
graphs = pydot.graph_from_dot_data(dot_str)
svg_str = graphs[0].create_svg()
SVG(svg_str)




In [ ]:
# let's try and predict D HERE

# This is for continous data.
# generate some toy data:
SIZE = 100000
a = np.random.normal(size=SIZE, scale = 1)
b = np.random.normal(size=SIZE, scale = 1)
c = np.random.normal(size=SIZE, scale = 1)
d = a + b + c + np.random.normal(size=SIZE, scale = 1)
e = d + np.random.normal(size=SIZE, scale = 1)
f= d + np.random.normal(size=SIZE, scale = 1)
g = d + np.random.normal(size=SIZE, scale = 1)

# load the data into a dataframe:
df = pd.DataFrame({'a' : a,'b' : b, 'c' : c, 'd' : d,'e' : e,'f':f, 'g':g})
import pandas as pd
from pycausal.pycausal import pycausal as pc
from pycausal import search as s
pc = pc()
pc.start_vm(java_max_heap_size = '2500M')
from pycausal import prior as p

tetrad = s.tetradrunner()
#GFCI = Greedy Fast Causal Interference (GFCI) 
# bdeu = Bayesian Dirichlet likelihood equivalence and uniform
tetrad.run(algoId = 'gfci', dfs = df, testId = 'sem-bic', scoreId = 'sem-bic', dataType = 'continuous',
           structurePrior = 1.0, samplePrior = 1.0, maxDegree = -1, maxPathLength = -1, 
           completeRuleSetUsed = False, faithfulnessAssumed = True, verbose = True)

import pydot
from IPython.display import SVG
dot_str = pc.tetradGraphToDot(tetrad.getTetradGraph())
graphs = pydot.graph_from_dot_data(dot_str)
svg_str = graphs[0].create_svg()
SVG(svg_str)

In [ ]:
pc = pc()
pc.start_vm(java_max_heap_size = '500M')
from pycausal import prior as p

tetrad = s.tetradrunner()
#GFCI = Greedy Fast Causal Interference (GFCI) 
# bdeu = Bayesian Dirichlet likelihood equivalence and uniform
tetrad.run(algoId = 'gfci', dfs = df, testId = 'sem-bic', scoreId = 'sem-bic', dataType = 'continuous',
           structurePrior = 1.0, samplePrior = 1.0, maxDegree = -1, maxPathLength = -1, 
           completeRuleSetUsed = False, faithfulnessAssumed = True, verbose = True)

import pydot
from IPython.display import SVG
dot_str = pc.tetradGraphToDot(tetrad.getTetradGraph())
graphs = pydot.graph_from_dot_data(dot_str)
print(len(graphs))
svg_str = graphs[0].create_svg()
SVG(svg_str)

# Trying some various ML models

In [34]:
#Synthetic data
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt
import pydot
from IPython.display import SVG

def gen_data():
    SIZE = 10000
    a = np.random.binomial(2, 0.2, size=SIZE)
    b = np.random.binomial(2, 0.3, size=SIZE)
    c = np.random.binomial(2, 0.4, size=SIZE)
    d = np.random.binomial(2, 0.5, size=SIZE)
    e = np.random.binomial(2, 0.6, size=SIZE)
    f= a + b + c + d + e + np.random.binomial(2, 0.5, size=SIZE)
    g = f + np.random.binomial(2, 0.5, size=SIZE)
    return pd.DataFrame({'a' : a,'b' : b, 'c' : c, 'd' : d,'e' : e,'f':f, 'g':g})


import scipy.stats as ss
import numpy as np
import matplotlib.pyplot as plt

def discrete_gauss(low, high, samples):
    x = np.arange(low, high)
    xU, xL = x + 0.5, x - 0.5 
    prob = ss.norm.cdf(xU, scale = 3) - ss.norm.cdf(xL, scale = 3)
    prob = prob / prob.sum() #normalize the probabilities so their sum is 1
    nums = np.random.choice(x, size = samples, p = prob)
    return nums

def gen_data():
    SIZE = 10000
    a = discrete_gauss(-3,3, SIZE)
    b = discrete_gauss(-3,3, SIZE)
    c = discrete_gauss(-3,3, SIZE)
    d = discrete_gauss(-3,3, SIZE)
    e = discrete_gauss(-3,3, SIZE)
    f= a + b + c + d + e + discrete_gauss(-3,3, SIZE)
    g = f + discrete_gauss(-3,3, SIZE)
    #for idx, i in enumerate(g):
    #    if i > np.mean(g):
    #        g[idx] = 1
    #    else:
    #        g[idx] = 0
    g[(g <= 3) & (g >= -3)] = 1
    g[g < -3] = 0

    g[g > 3] = 2
    return pd.DataFrame({'a' : a,'b' : b, 'c' : c, 'd' : d,'e' : e,'f':f, 'g':g})

df = gen_data()


In [51]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys
from sklearn.metrics import roc_auc_score, average_precision_score, mean_squared_error, accuracy_score
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression, Perceptron
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import GaussianNB, BernoulliNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, AdaBoostClassifier, BaggingClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
import pandas as pd

from pycausal import search as s

def get_CG(df, tetrad):
    tetrad.run(algoId = 'gfci', dfs = df, testId = 'sem-bic', scoreId = 'sem-bic', dataType = 'continuous',
           structurePrior = 1.0, samplePrior = 1.0, maxDegree = -1, maxPathLength = -1, 
           completeRuleSetUsed = False, faithfulnessAssumed = True, verbose = True)
    #tetrad.run(algoId = 'gfci', dfs = df, testId = 'bdeu', scoreId = 'bdeu', dataType = 'discrete',
    #       structurePrior = 1.0, samplePrior = 1.0, maxDegree = 3, faithfulnessAssumed = True, verbose = True)


    return tetrad.getTetradGraph()

def get_MB(graph, var, pc):
    parents = set()
    for i in pc.extractTetradGraphEdges(graph):
        if i[-1] == var and i[3:5] == '->':
            parents.add(i[0])
    return parents

from pycausal.pycausal import pycausal as pc
pc = pc()
pc.start_vm(java_max_heap_size = '5000M')
tetrad = s.tetradrunner()
def run_models(models, model_names, x, y, num_folds=5):
    '''
    given an sklearn model, data, and number of folds returns mean and std dev of n-fold cross validated test auroc.
    '''
    results = []
    violations = np.zeros(len(models))
    mean = np.zeros((len(models), num_folds))
    skf = StratifiedKFold(n_splits=num_folds)
    fold = 0
    for train_index, test_index in skf.split(x, y):
        x_train, x_test = x[train_index], x[test_index]
        y_train, y_test = y[train_index], y[test_index]
        for idx, model in enumerate(models):
            model.fit(x_train, y_train)
            original_df = pd.DataFrame(x_test, columns = ['a', 'b', 'c', 'd', 'e', 'f'])

            original_targets = pd.DataFrame(y_test, columns = ['g'])
            original_df = original_df.join(original_targets)
            test_df = pd.DataFrame(x_test, columns = ['a', 'b', 'c', 'd', 'e', 'f'])
            test_targets = pd.DataFrame(model.predict(x_test), columns = ['g'])
            test_df = test_df.join(test_targets)
            #print(get_MB(get_CG(test_df), 'g'))
            print("Error:", model_names[idx], accuracy_score(y_test, model.predict(x_test)))
            mean[idx][fold] = accuracy_score(y_test, model.predict(x_test))
            if get_MB(get_CG(original_df, tetrad), 'g', pc) != get_MB(get_CG(test_df, tetrad), 'g', pc):
                print("Violation:", get_MB(get_CG(original_df, tetrad), 'g', pc) , get_MB(get_CG(test_df, tetrad), 'g', pc))
                violations[idx] += 1
            #pc.stop_vm()
        fold += 1
    
    print("Violations = ", violations)
    for i in range(len(violations)):
        print("Model_name = ", model_names[i], "Violations = ", violations[i])
        print("Accuracy = ", np.mean(mean[i]), np.std(mean[i]))
    return np.mean(results), np.std(results)

X = df[['a', 'b', 'c', 'd', 'e', 'f']].values
y = df['g'].values

models = [LogisticRegression(), 
          Perceptron(),  
          DecisionTreeClassifier(),
          LinearSVC(),
          GaussianNB(),
          BernoulliNB(),
          LinearDiscriminantAnalysis(),
          RandomForestClassifier(),
          ExtraTreesClassifier(),
          #AdaBoostClassifier(),
          #BaggingClassifier(),
          #GradientBoostingClassifier(),
          #MLPClassifier()
         ]
model_names = ['LogisticRegression()', 
          'Perceptron()',  
          'DecisionTreeClassifier()',
          'LinearSVC()',
          'GaussianNB()',
          'BernoulliNB()',
          'LinearDiscriminantAnalysis()',
          'RandomForestClassifier()',
          'ExtraTreesClassifier()', 
          #'AdaBoostClassifier()',
          #'BaggingClassifier()',
          #'GradientBoostingClassifier()',
          #'MLPClassifier()'
         ]

run_models(models,model_names, X,y)

Error: LogisticRegression() 0.816591704147926
Error: Perceptron() 0.7161419290354822


/home/tkyono/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.perceptron.Perceptron'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


Error: DecisionTreeClassifier() 0.7706146926536732
Error: LinearSVC() 0.8035982008995503
Error: GaussianNB() 0.8285857071464268
Error: BernoulliNB() 0.697151424287856
Error: LinearDiscriminantAnalysis() 0.8260869565217391
Error: RandomForestClassifier() 0.8025987006496752
Error: ExtraTreesClassifier() 0.7956021989005497
Error: LogisticRegression() 0.8045977011494253
Error: Perceptron() 0.7241379310344828


/home/tkyono/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.perceptron.Perceptron'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


Error: DecisionTreeClassifier() 0.7531234382808596
Error: LinearSVC() 0.7981009495252374
Error: GaussianNB() 0.8185907046476761
Error: BernoulliNB() 0.6956521739130435
Error: LinearDiscriminantAnalysis() 0.8170914542728636
Error: RandomForestClassifier() 0.782608695652174
Error: ExtraTreesClassifier() 0.7856071964017991
Error: LogisticRegression() 0.7925


/home/tkyono/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.perceptron.Perceptron'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


Error: Perceptron() 0.749
Violation: {'f'} {'a', 'f'}
Error: DecisionTreeClassifier() 0.7465
Error: LinearSVC() 0.79
Error: GaussianNB() 0.817
Error: BernoulliNB() 0.702
Error: LinearDiscriminantAnalysis() 0.813
Error: RandomForestClassifier() 0.7935
Error: ExtraTreesClassifier() 0.7765
Error: LogisticRegression() 0.8285
Error: Perceptron() 0.751


/home/tkyono/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.perceptron.Perceptron'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


Violation: {'f'} {'f', 'a', 'd'}
Error: DecisionTreeClassifier() 0.7705
Error: LinearSVC() 0.8215
Error: GaussianNB() 0.8405
Error: BernoulliNB() 0.72
Error: LinearDiscriminantAnalysis() 0.8465
Error: RandomForestClassifier() 0.805
Error: ExtraTreesClassifier() 0.794
Error: LogisticRegression() 0.8168168168168168


/home/tkyono/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.perceptron.Perceptron'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


Error: Perceptron() 0.7702702702702703
Error: DecisionTreeClassifier() 0.7537537537537538
Error: LinearSVC() 0.8083083083083084
Error: GaussianNB() 0.8173173173173173
Error: BernoulliNB() 0.6866866866866866
Error: LinearDiscriminantAnalysis() 0.8268268268268268
Error: RandomForestClassifier() 0.7952952952952953
Error: ExtraTreesClassifier() 0.7812812812812813
Violations =  [0. 2. 0. 0. 0. 0. 0. 0. 0.]
Model_name =  LogisticRegression() Violations =  0.0
Accuracy =  0.8118012444228336 0.012258727345077854
Model_name =  Perceptron() Violations =  2.0
Accuracy =  0.742110026068047 0.01957979057196889
Model_name =  DecisionTreeClassifier() Violations =  0.0
Accuracy =  0.7588983769376573 0.009852984588645293
Model_name =  LinearSVC() Violations =  0.0
Accuracy =  0.8043014917466191 0.010538664745915019
Model_name =  GaussianNB() Violations =  0.0
Accuracy =  0.824398745822284 0.009114849893716805
Model_name =  BernoulliNB() Violations =  0.0
Accuracy =  0.7002980569775171 0.011025589297987

/home/tkyono/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/tkyono/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/tkyono/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:140: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/home/tkyono/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:110: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/home/tkyono/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:132: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


(nan, nan)

In [ ]:
get_CG(df, tetrad)
dot_str = pc.tetradGraphToDot(tetrad.getTetradGraph())
graphs = pydot.graph_from_dot_data(dot_str)
print(len(graphs))
svg_str = graphs[0].create_svg()
SVG(svg_str)


In [47]:
# REMEMBER THAT STRATIFIED KFOLD PRESERVES SAMPLES
X = df[['a', 'b', 'c', 'd', 'e', 'f']].values
y = df['g'].values
skf = StratifiedKFold(n_splits=10)
for train_index, test_index in skf.split(X, y):
    x_train, x_test = X[train_index], X[test_index]
    y_train, Y_test = y[train_index], y[test_index]
    print(test_index[:30])
    print(Y_test[:30])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[0 2 0 0 1 1 0 1 1 0 1 1 1 1 0 0 1 0 0 0 1 1 0 0 0 1 0 0 1 1]
[ 985  987  989  990  991  992  993  994  995  996  998  999 1000 1001
 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015
 1016 1017]
[0 0 1 1 1 0 1 1 0 0 1 0 0 1 0 1 1 0 0 0 1 1 1 1 0 1 1 1 1 0]
[1953 1955 1956 1957 1958 1961 1964 1965 1966 1968 1969 1972 1981 1983
 1986 1990 1992 1993 1994 1995 2002 2003 2005 2007 2008 2010 2011 2012
 2015 2017]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[2932 2968 2978 2980 2983 2984 2987 2988 2989 2990 2992 2994 2995 2999
 3004 3006 3007 3009 3010 3011 3012 3013 3016 3018 3019 3021 3022 3023
 3025 3026]
[2 2 2 2 0 0 2 0 0 0 0 2 0 0 0 0 0 0 0 0 0 2 0 2 0 0 0 0 0 0]
[3841 3848 3858 3874 3880 3897 3939 3982 3983 3985 3986 3988 3989 3992
 3994 3996 3997 3998 3999 4000 4008 4010 4015 4016 4020 4021 4027 4029
 4030 4031]
[2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 

In [50]:
y[[3841, 3848]]

array([2, 2])

In [ ]:
logreg = LogisticRegression()
print('log reg', mse_sklearn(logreg,X,y))
perc = Perceptron()
print('perceptron', mse_sklearn(perc,X,y))
neigh = KNeighborsClassifier(n_neighbors=2)
print('knn', mse_sklearn(neigh,X,y))
tree = DecisionTreeClassifier()
print('decision tree',mse_sklearn(tree,X,y))
svc = LinearSVC()
print('linear svm',mse_sklearn(svc,X,y))
gnb = GaussianNB()
print('gnb',mse_sklearn(gnb,X,y))
bnb = BernoulliNB()
print('bnb', mse_sklearn(bnb,X,y))
lda = LinearDiscriminantAnalysis()
print('lda', mse_sklearn(lda,X,y))
rfc = RandomForestClassifier()
print('random forest',mse_sklearn(rfc,X,y))
etc = ExtraTreesClassifier()
print('ext. rand. trees',mse_sklearn(etc,X,y))
ada = AdaBoostClassifier()
print('ada',mse_sklearn(ada,X,y))
bc = BaggingClassifier()
print('baggging',mse_sklearn(bc,X,y))
gdc = GradientBoostingClassifier()
print('grad boost',mse_sklearn(gdc,X,y))
#xgb = XGBClassifier()
#print('xgb', mse_sklearn(xgb,X,y))
mlp = MLPClassifier()
print('mlp',mse_sklearn(mlp,X,y))

In [ ]:
X